//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnet.Api.Poc.Data.Entities.kaiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentSetting
    {
        public int EnvironmentSettingID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModUser { get; set; }
    }
}
