//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnet.Api.Poc.Data.Entities.Abc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int UserID { get; set; }
        public int InventoryID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public string State { get; set; }
        public string Firm { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> DripDate { get; set; }
        public string PrintFileName { get; set; }
        public Nullable<System.DateTime> ProofDate { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> ModUser { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public bool IsProofMade { get; set; }
        public bool IsPrintFileMade { get; set; }
        public bool IsError { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> RootParentID { get; set; }
        public Nullable<decimal> PrintCost { get; set; }
        public Nullable<decimal> PrintChargeBackCost { get; set; }
        public Nullable<decimal> FulfillmentCost { get; set; }
        public Nullable<decimal> PrintSurcharge { get; set; }
        public Nullable<decimal> PostageEstimate { get; set; }
        public string OrderingType { get; set; }
        public Nullable<decimal> LineItemCost { get; set; }
        public bool IsRemoved { get; set; }
        public bool IsInProgress { get; set; }
        public string SortOrder { get; set; }
        public int NumOfLineItems { get; set; }
        public int NumOfLineItemQty { get; set; }
        public int NumOfKitting { get; set; }
        public int NumOfCoreKitting { get; set; }
        public int NumOfKitLineItems { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string RoleIDs { get; set; }
        public string ContactID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> QtyType { get; set; }
        public short CartLineItemTypeID { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public bool IsPrintCostApproved { get; set; }
        public string ExternalPartNumber { get; set; }
        public Nullable<bool> IsHiddenFromUI { get; set; }
        public bool IsHold { get; set; }
        public Nullable<int> OriginalCartID { get; set; }
    }
}
